CREATE TABLE Users
(
    UserId       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Name         VARCHAR2(255),
    Passwordhash VARCHAR2(255),
    Role         VARCHAR2(10) CHECK (Role IN ('Player', 'Admin'))
);

CREATE TABLE Players
(
    Id           NUMBER PRIMARY KEY,
    GamesPlayed  NUMBER,
    HighScore    NUMBER,
    AverageScore NUMBER,
    LastPlayed   TIMESTAMP,
    CONSTRAINT fk_player_user FOREIGN KEY (Id) REFERENCES Users (UserId)
);

CREATE TABLE Admins
(
    Id             NUMBER PRIMARY KEY,
    CreatedAt      TIMESTAMP,
    CreatedBy      VARCHAR2(255),
    CanDeleteUsers NUMBER(1),
    IsActive       NUMBER(1),
    CONSTRAINT fk_admin_user FOREIGN KEY (Id) REFERENCES Users (UserId)
);





