<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net9.0-windows</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UseWPF>true</UseWPF>
        <RootNamespace>QuizApp</RootNamespace>
        <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Core\Core.csproj" />
        <ProjectReference Include="..\Infrastructure\Infrastructure.csproj" />
        <ProjectReference Include="..\Logic\Logic.csproj" />
        <Folder Include="ViewModels"/>
        <Folder Include="Views"/>
        <ProjectReference Include="..\Tests\Tests.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <None Include="..\applicationsettings.json">
            <Link>appsettings.json</Link>
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
    </ItemGroup>
    <ItemGroup>
        <None Include="..\Infrastructure\docker\init-schema.sql">
            <Link>init-schema.sql</Link>
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Include="..\Infrastructure\docker\init-data.sql">
            <Link>init-data.sql</Link>
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
    </ItemGroup>
    <ItemGroup>
      <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    </ItemGroup>
</Project>
