<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net9.0-windows</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UseWPF>true</UseWPF>
        <RootNamespace>Meilenstein03</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Core\Core.csproj"/>
        <ProjectReference Include="..\Infrastructure\Infrastructure.csproj"/>
        <ProjectReference Include="..\Logic\Logic.csproj"/>
        <ProjectReference Include="..\Tests\Tests.csproj"/>
    </ItemGroup>

</Project>
