<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>QuizApp.Core</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Oracle.ManagedDataAccess" Version="23.8.0"/>
    </ItemGroup>

</Project>
