DROP TABLE MultipleChoiceQuestion CASCADE CONSTRAINTS;
DROP TABLE EstimateQuestion CASCADE CONSTRAINTS;
DROP TABLE TrueFalseQuestion CASCADE CONSTRAINTS;
DROP TABLE SortQuestion CASCADE CONSTRAINTS;
DROP TABLE OpenQuestion CASCADE CONSTRAINTS;


CREATE TABLE MultipleChoiceQuestion (
                                        Id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                        Question VARCHAR2(255),
                                        Typ VARCHAR2(20),
                                        Difficulty NUMBER CHECK (Difficulty IN (0,1,2)),
                                        Category VARCHAR2(50),
                                        RightAnswer VARCHAR2(255),
                                        FalseAnswer1 VARCHAR2(255),
                                        FalseAnswer2 VARCHAR2(255),
                                        FalseAnswer3 VARCHAR2(255)
);

CREATE TABLE EstimateQuestion (
                                  Id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                  Question VARCHAR2(255),
                                  Typ VARCHAR2(20),
                                  Difficulty NUMBER CHECK (Difficulty IN (0,1,2)),
                                  Category VARCHAR2(50),
                                  RightAnswer VARCHAR2(255)
);

CREATE TABLE TrueFalseQuestion (
                                   Id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                   Question VARCHAR2(4000),
                                   Typ VARCHAR2(20),
                                   Difficulty NUMBER CHECK (Difficulty IN (0,1,2)),
                                   Category VARCHAR2(50),
                                   TrueFalse NUMBER(1) CHECK (TrueFalse IN (0,1))  -- 0 = false, 1 = true
);

CREATE TABLE SortQuestion (
                              Id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              Question VARCHAR2(255),
                              Typ VARCHAR2(20),
                              Difficulty NUMBER CHECK (Difficulty IN (0,1,2)),
                              Category VARCHAR2(50),
                              Place1 VARCHAR2(255),
                              Place2 VARCHAR2(255),
                              Place3 VARCHAR2(255),
                              Place4 VARCHAR2(255)
);

CREATE TABLE OpenQuestion (
                              Id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              Question VARCHAR2(255),
                              Typ VARCHAR2(20),
                              Difficulty NUMBER CHECK (Difficulty IN (0,1,2)),
                              Category VARCHAR2(50),
                              Answer VARCHAR2(255) 
);

