CREATE TABLE MultipleChoiceQuestion (
                                        Id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                        Question VARCHAR2(255),
                                        Typ VARCHAR2(20),
                                        Difficulty NUMBER CHECK (Difficulty IN (0,1,2)),
                                        Category VARCHAR2(50),
                                        RightAnswer VARCHAR2(255),
                                        FalseAnswer1 VARCHAR2(255),
                                        FalseAnswer2 VARCHAR2(255),
                                        FalseAnswer3 VARCHAR2(255)
);

CREATE TABLE EstimateQuestion (
                                  Id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                  Question VARCHAR2(255),
                                  Typ VARCHAR2(20),
                                  Difficulty NUMBER CHECK (Difficulty IN (0,1,2)),
                                  Category VARCHAR2(50),
                                  RightAnswer VARCHAR2(255)
);

CREATE TABLE TrueFalseQuestion (
                                   Id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                   Question VARCHAR2(4000),
                                   Typ VARCHAR2(20),
                                   Difficulty NUMBER CHECK (Difficulty IN (0,1,2)),
                                   Category VARCHAR2(50),
                                   TrueFalse NUMBER(1) CHECK (TrueFalse IN (0,1))  -- 0 = false, 1 = true
);

CREATE TABLE SortQuestion (
                              Id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              Question VARCHAR2(255),
                              Typ VARCHAR2(20),
                              Difficulty NUMBER CHECK (Difficulty IN (0,1,2)),
                              Category VARCHAR2(50),
                              Place1 VARCHAR2(255),
                              Place2 VARCHAR2(255),
                              Place3 VARCHAR2(255),
                              Place4 VARCHAR2(255)
);

CREATE TABLE OpenQuestion (
                              Id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              Question VARCHAR2(255),
                              Typ VARCHAR2(20),
                              Difficulty NUMBER CHECK (Difficulty IN (0,1,2)),
                              Category VARCHAR2(50),
                              Answer VARCHAR2(255) 
);

CREATE TABLE Users
(
    UserId       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Name         VARCHAR2(255),
    Passwordhash VARCHAR2(255),
    Role         VARCHAR2(10) CHECK (Role IN ('Player', 'Admin'))
);

CREATE TABLE Players
(
    Id           NUMBER PRIMARY KEY,
    GamesPlayed  NUMBER,
    HighScore    NUMBER,
    AverageScore NUMBER,
    LastPlayed   TIMESTAMP,
    CONSTRAINT fk_player_user FOREIGN KEY (Id) REFERENCES Users (UserId)
);

CREATE TABLE Admins
(
    Id             NUMBER PRIMARY KEY,
    CreatedAt      TIMESTAMP,
    CreatedBy      VARCHAR2(255),
    IsActive       NUMBER(1),
    CONSTRAINT fk_admin_user FOREIGN KEY (Id) REFERENCES Users (UserId)
);





